services:
  - type: web
    name: qr-order-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SERVICE_ACCOUNT_JSON
        sync: false

    nativePackages:
      - libzbar0
