services:
  - type: web
    name: qr-drive-service
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      python main.py

    nativePackages:
      - libzbar0
